fix: portfolio table sorting
balancer/frontend-monorepo pull request #334
Opened 2024-12-17 12:06 UTC by alter-eggo

This pr fixes portfolio table sorting, mentioned [here](https://discord.com/channels/638460494168064021/1317147929374490685/1317147992234397789)

2024-12-17 15:33 UTC, garethfuller commented
@alter-eggo Can you merge in main and fix the PR please.

2024-12-18 08:39 UTC, agualis requested changes

2024-12-18 08:39 UTC, agualis commented on packages/lib/modules/pool/PoolDetail/PoolActivityTable/PoolActivityTable.tsx
> +            getRowId={([_timestamp, _value, poolActivityMetaData]) => poolActivityMetaData.id}
Lint problems here

2024-12-18 08:39 UTC, agualis commented on packages/lib/modules/pool/PoolList/PoolListTable/PoolListTable.tsx
> +        getRowId={item => item.id}
More lint issues

2024-12-18 08:39 UTC, agualis commented on packages/lib/shared/components/tables/PaginatedTable.tsx
> +export function PaginatedTable<T extends any>({
More lint issues

2024-12-19 07:51 UTC, agualis approved these changes

2024-12-19 08:45 UTC, merged