spike: inject project config from app
balancer/frontend-monorepo pull request #393
Opened 2024-12-30 12:46 UTC by groninge01

2025-01-14 09:30 UTC, groninge01 commented on apps/frontend-v3/app/(app)/pools/cow/page.tsx
> -            <PoolList fixedPoolTypes={[GqlPoolType.CowAmm]} hidePoolTags={['VE8020']} />
can't do this anymore
alternative: create a separate app for cow -> cow-pools.balancer.fi

2025-01-14 09:42 UTC, groninge01 commented on packages/lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx
> +  const shouldBlockCustom = isMaBeetsPool(pool.id)
this hsould maybe somehow also move to the project config (inclusing the reason string)

2025-01-16 13:47 UTC, garethfuller commented on apps/frontend-v3/app/(app)/pools/cow/page.tsx
> -            <PoolList fixedPoolTypes={[GqlPoolType.CowAmm]} hidePoolTags={['VE8020']} />
Not a fan of having to create another app for this feature tbh.

2025-01-16 14:01 UTC, groninge01 commented on apps/frontend-v3/app/(app)/pools/cow/page.tsx
> -            <PoolList fixedPoolTypes={[GqlPoolType.CowAmm]} hidePoolTags={['VE8020']} />
it would also be easier with theming and could remove swap & vebal from navbar?
another alternative is to hide the pool tag in the pool filter as other stuff is also already dependent on `isCowPath`

2025-01-16 15:49 UTC, agualis requested changes

2025-01-17 07:41 UTC, groninge01 commented on packages/lib/modules/pool/PoolDetail/PoolHeader/PoolHeader.tsx
> +  const shouldBlockCustom = isMaBeetsPool(pool.id)
ok that kind of how i had it before :)
i've reverted it back with your suggestions

2025-01-17 07:43 UTC, groninge01 commented on apps/beets-frontend-v3/app/(app)/pools/[chain]/[variant]/[id]/add-liquidity/[[...txHash]]/layout.tsx
> +  if (shouldBlockAddLiquidity(pool, shouldBlockCustom)) {
updated it (see above also)

2025-01-17 07:46 UTC, groninge01 commented on apps/beets-frontend-v3/lib/components/navs/NavBarContainer.tsx
> +      /* customLinksBefore={
because it is a daniel component :)
but i have removed the comment and the component now as it's probably not going to be used anymore

2025-01-17 07:51 UTC, groninge01 commented on packages/lib/config/config.types.ts
> +  displayType: PoolListDisplayType
done!

2025-01-17 07:54 UTC, groninge01 commented on packages/lib/modules/pool/PoolList/PoolListPoolDisplay.tsx
> +  switch (displayType) {
done!

2025-01-17 11:14 UTC, groninge01 commented on apps/beets-frontend-v3/lib/components/footer/FooterContainer.tsx
> +      socialLinks={getSocialLinks(PROJECT_CONFIG.externalLinks.discordUrl)}
i moved all nav & footer data into the project configs

2025-01-17 12:29 UTC, groninge01 commented
> The only blocker would be the CoW AMM filter issue. I don't fully understand why it is not possible to keep the same logic.

also for @garethfuller 
i think i can just leave it as is for now?

2025-01-17 12:41 UTC, agualis approved these changes

2025-01-20 14:48 UTC, groninge01 commented
> Somehow this removes the description work I did last week? Unless it's just not been merged in? <img alt="Screenshot 2025-01-20 at 13 59 45" width="973" src="https://private-user-images.githubusercontent.com/2406506/404902881-799538df-b9d4-4ae6-bf65-c8ac19cb248d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczODQ2MDEsIm5iZiI6MTczNzM4NDMwMSwicGF0aCI6Ii8yNDA2NTA2LzQwNDkwMjg4MS03OTk1MzhkZi1iOWQ0LTRhZTYtYmY2NS1jOGFjMTljYjI0OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTQ0NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE0MzQwNWIzNDMzNTM5NjE5YmU5ZGI2M2Y5MDAzZTAyOWRmZmJlZjkyM2ZlNjMzMmExZGQxMjYwMmIzMWRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AT2UJAItC3DGggOzx5ty259UHL2XWefC00DFuQuAMMw

> Somehow this removes the description work I did last week? Unless it's just not been merged in? <img alt="Screenshot 2025-01-20 at 13 59 45" width="973" src="https://private-user-images.githubusercontent.com/2406506/404902881-799538df-b9d4-4ae6-bf65-c8ac19cb248d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczODQ2MDEsIm5iZiI6MTczNzM4NDMwMSwicGF0aCI6Ii8yNDA2NTA2LzQwNDkwMjg4MS03OTk1MzhkZi1iOWQ0LTRhZTYtYmY2NS1jOGFjMTljYjI0OGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTQ0NTAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE0MzQwNWIzNDMzNTM5NjE5YmU5ZGI2M2Y5MDAzZTAyOWRmZmJlZjkyM2ZlNjMzMmExZGQxMjYwMmIzMWRjMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.AT2UJAItC3DGggOzx5ty259UHL2XWefC00DFuQuAMMw">

that was not merged from main yet, had a conflict so it's merged in now

2025-01-20 15:25 UTC, merged